# Generated by Django 4.1.3 on 2022-11-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessview_application', '0005_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
